load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@svetoch_bazel_lib//tools/lint/py:black.bzl", "py_lint")
load("@svetoch_bazel_lib_py_deps//:requirements.bzl", "requirement")

py_lint()

py_binary(
    name = "prepare",
    srcs = glob(
        ["*.py"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "@svetoch_bazel_lib//rod/libs/py/settings",
        "@svetoch_bazel_lib//rod/libs/py/tf",
        "@svetoch_bazel_lib//rod/scripts/init:prepare",
        requirement("click"),
    ],
)
