certificates:
  enabled: true
  issuers:
    selfsigned:
      enabled: true
  certs:
    authn:
      enabled: true
      ##MASKED##issuerRef:
      ##MASKED##  kind: ClusterIssuer
      ##MASKED##  name: '{{ printf "letsencrypt-%s" .Values.global.ingress.class }}'
  cluster_issuers:
    letsencrypt:
      enabled: true


gen-secrets:
  enabled: true


controller:
  enabled: true
