ingresses:
  server:
    enabled: true

argocd:
  enabled: true
  global:
    image:
      repository: cr.yandex/crp3t3boffavo7mraal9/argocd
      tag: v3.2.11-yc

redis:
  enabled: true

probes:
  enabled: true
  probes:
    argocd:
      enabled: true

prometheus-rules:
  enabled: true
  PrometheusAlerts:
    argocd:
      AbsentMetricCritical:
        enabled: true
        rules:
          probe_success:
            enabled: true
