kong-plugins:
  enabled: true

certificates:
  enabled: true
  issuers:
    selfsigned:
      enabled: true
  certs:
    webhook:
      enabled: true
  cluster_issuers:
    letsencrypt:
      enabled: true

kong:
  enabled: true
  replicaCount: 2
  ingressController:
    admissionWebhook:
      enabled: true
