grafana-operator:
  enabled: true

ingresses:
  main:
    enabled: true

grafana-main:
  enabled: true

datasource:
  enabled: true

common-dashboard:
  enabled: true

common-google-cloud-dashboard:
  enabled: true
