grafana-operator:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 150m
      memory: 150Mi

ingresses:
  main:
    enabled: true

grafana-main:
  enabled: true

datasource:
  enabled: true

common-dashboard:
  enabled: true

common-google-cloud-dashboard:
  enabled: true
