load("@rules_multirun//:defs.bzl", "command", "multirun")
load("//scripts/e2e/prepare:prepare.bzl", "get_e2e_prepare_args")

prepare_args = get_e2e_prepare_args()

command(
    name = "prepare",
    arguments = prepare_args,
    command = "//scripts/e2e/prepare",
)

command(
    name = "infra_create",
    command = "//scripts/init",
)

command(
    name = "infra_destroy",
    command = "//scripts/e2e/poststeps:destroy",
)

multirun(
    name = "e2e",
    commands = [
        "prepare",
        "infra_create",
    ],
)
