module(name = "infrared")

###########
# Bazel
###########
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

bazel_dep(name = "buildifier_prebuilt", version = "8.0.1", dev_dependency = True)

bazel_dep(name = "aspect_bazel_lib", version = "2.14.0")

bazel_lib_toolchains = use_extension("@aspect_bazel_lib//lib:extensions.bzl", "toolchains")
use_repo(bazel_lib_toolchains, "zstd_toolchains")

bazel_dep(name = "rules_pkg", version = "1.0.1")
bazel_dep(name = "rules_multirun", version = "0.10.0")

######################
# Terraform support
######################

bazel_dep(name = "rules_tf")
git_override(
    module_name = "rules_tf",
    commit = "2cb8d57eba4c190d37914c44af17a7d0b7b4f07f",
    remote = "https://github.com/ggramal/rules_tf",
)

tf = use_extension("@rules_tf//tf:extensions.bzl", "tf")
tf.toolchain(version = "1.7.4")
use_repo(tf, "tf_executable")

load_json_file = use_repo_rule("//tools/repo_rules:load_json_file.bzl", "load_json_file")

load_json_file(
    name = "tfvars",
    src = "//:terraform/terraform.tfvars.json",
    variable_name = "tfvars",
)

###################
# Container support
###################

bazel_dep(name = "rules_oci", version = "2.2.2")
bazel_dep(name = "rules_distroless", version = "0.5.1")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "logical-backup",
    #v1.14.0
    digest = "sha256:c8c600e4ca0acdfb7843e2943ae0274763c8f1c03fef5245dc0912a4cbd15c18",
    image = "ghcr.io/zalando/postgres-operator/logical-backup",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
oci.pull(
    name = "postgres-exporter",
    #v0.17.1
    digest = "sha256:38606faa38c54787525fb0ff2fd6b41b4cfb75d455c1df294927c5f611699b17",
    image = "quay.io/prometheuscommunity/postgres-exporter",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
oci.pull(
    name = "spilo17",
    #v17-bb39d81
    digest = "sha256:69bf8719ff25c0f1e7bb2de464ed89c3aa459f4816f752ed2da146a7d451a96b",
    image  = "docker.io/gramal/spilo",
    platforms = [
        "linux/amd64",
    ],
)
oci.pull(
    name = "spilo15",
    #15-f0c5f71
    digest = "sha256:0838d144f4fdbe01d5ec161f5fe68fd40250dd96268f2ea2097e8a6ab82b9db3",
    image  = "docker.io/gramal/spilo",
    platforms = [
        "linux/amd64"
    ],
)
use_repo(
    oci,
    "spilo15",
    "spilo15_linux_amd64",
    "spilo17",
    "spilo17_linux_amd64",
    "logical-backup",
    "logical-backup_linux_amd64",
    "logical-backup_linux_arm64",
    "postgres-exporter",
    "postgres-exporter_linux_amd64",
    "postgres-exporter_linux_arm64",
)

apt = use_extension("@rules_distroless//apt:extensions.bzl", "apt")

#bazel run @noble//:lock
apt.install(
    name = "noble",
    lock = "//deps/deb:noble.lock.json",
    manifest = "//deps/deb:noble.yaml",
)
use_repo(apt, "noble")

http_archive(
    name = "ca-certificates",
    build_file_content = "exports_files([\"data.tar.zst\"])",
    sha256 = "641de77d8f142cfd62a1a6f964ba67b20754d3337c480efb529d086075a06c9a",
    type = ".deb",
    urls = ["https://snapshot.ubuntu.com/ubuntu/20240917T000000Z/pool/main/c/ca-certificates/ca-certificates_20240203_all.deb"],
)

http_file(
    name = "bazelisk",
    downloaded_file_path = "bazelisk",
    sha256 = "fd8fdff418a1758887520fa42da7e6ae39aefc788cf5e7f7bb8db6934d279fc4",
    url = "https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-linux-amd64",
)

##################
# Python support
##################
bazel_dep(name = "aspect_rules_py", version = "1.3.2")
bazel_dep(name = "rules_python", version = "1.2.0")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.11",
)
use_repo(python, python = "python_versions")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "py_deps",
    python_version = "3.11",
    requirements_lock = "//deps/py:requirements_lock_3_11.txt",
)
use_repo(pip, "py_deps")
