module(name = "rod")

###########
# Bazel
###########
bazel_dep(name = "buildifier_prebuilt", version = "8.5.1")
bazel_dep(name = "aspect_bazel_lib", version = "2.22.5")

bazel_lib_toolchains = use_extension("@aspect_bazel_lib//lib:extensions.bzl", "toolchains")
use_repo(bazel_lib_toolchains, "zstd_toolchains")

bazel_dep(name = "rules_multirun", version = "0.10.0")
bazel_dep(name = "svetoch_bazel_lib")
git_override(
    module_name = "svetoch_bazel_lib",
    commit = "21c1c5c2b37e0e6c7d7f1206c26f78a1a91ed83c",
    remote = "https://github.com/svetoch-dev/bazel-lib",
)

######################
# Binary tools support
######################
bazel_dep(name = "rules_bin_tools")
git_override(
    module_name = "rules_bin_tools",
    commit = "d3fefc59031fe28fcc41918f8e9df752c58c3c49",
    remote = "https://github.com/ggramal/rules_bin_tools",
)

tools = use_extension("@rules_bin_tools//tools:extensions.bzl", "tools")
tools.download(
    helm_version = "v3.18.4",
)
use_repo(tools, "helm_executable")

######################
# Terraform support
######################

bazel_dep(name = "rules_tf")
git_override(
    module_name = "rules_tf",
    commit = "972e20e677514021345d095f258f2e5e31d5a3c6",
    remote = "https://github.com/ggramal/rules_tf",
)

tf = use_extension("@rules_tf//tf:extensions.bzl", "tf")
tf.toolchain(version = "1.14.4")
use_repo(tf, "tf_executable")

register_toolchains(
    "@tf_executable//:all",
)

load_file = use_extension("@svetoch_bazel_lib//tools:extensions.bzl", "load_file")
load_file.json(
    name = "tfvars",
    src = "//:terraform.tfvars.json",
    variable_name = "tfvars",
)
use_repo(load_file, "tfvars")

override_repo(
    load_file,
    svetoch_bazel_lib_tfvars = "tfvars",
)

###################
# Container support
###################

bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "rules_distroless", version = "0.6.2")

##################
# Python support
##################
bazel_dep(name = "aspect_rules_py", version = "1.3.2")
bazel_dep(name = "rules_python", version = "1.2.0")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.11",
)
use_repo(python, python = "python_versions")

svetoch_bazel_lib_pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
use_repo(svetoch_bazel_lib_pip, "svetoch_bazel_lib_py_deps")
