rabbitmq-cluster-operator:
  enabled: true
  clusterOperator:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 22Mi
    nodeSelector:
      apps-spot: "true"
    tolerations:
      - key: "apps-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  msgTopologyOperator:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 22Mi
    nodeSelector:
      apps-spot: "true"
    tolerations:
      - key: "apps-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

rabbitmq-main:
  enabled: false
