load("@rules_multirun//:defs.bzl", "command", "multirun")

command(
    name = "prepare",
    command = "//tests/e2e/prepare",
)

command(
    name = "infra_create",
    command = "@svetoch_bazel_lib//rod/scripts/init",
)

command(
    name = "infra_destroy",
    command = "//tests/e2e/poststeps:destroy",
)

multirun(
    name = "e2e",
    commands = [
        "prepare",
        "infra_create",
    ],
)
