postgres-operator:
  enabled: true
  nodeSelector:
    apps-spot: "true"
  tolerations:
  - key: "apps-spot"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  resources:
    limits:
      cpu: 350m
      memory: 150Mi
    requests:
      cpu: 10m
      memory: 35Mi
  configLogicalBackup:
    logical_backup_provider: "gcs"
    logical_backup_docker_image: "{{ .Values.global.registry.url}}/pg-logical-backup:v1.14.0-1"
    logical_backup_schedule: "25 00 * * *"
  # resources for logical backup pod, if empty configPostgresPodResources will be used
    logical_backup_cpu_limit: "2"
    logical_backup_cpu_request: 200m
    logical_backup_memory_limit: 500Mi
    logical_backup_memory_request: 300Mi
  configMajorVersionUpgrade:
    target_major_version: '15'
