postgres-operator:
  enabled: true
  nodeSelector:
    apps-spot: "true"
  tolerations:
  - key: "apps-spot"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  configLogicalBackup:
    logical_backup_schedule: "25 00 * * *"
