redis-operator:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 300m
      memory: 100Mi
  nodeSelector:
    apps-spot: "true"
  tolerations:
    - key: "apps-spot"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
