load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@py_deps//:requirements.bzl", "requirement")
load("//tools/lint/py:black.bzl", "py_lint")
load(":prepare.bzl", "prepare")

py_lint()

prepare()

py_binary(
    name = "tfvars",
    srcs = ["tfvars.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//libs/py/helpers",
        requirement("click"),
    ],
)
