load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@svetoch_bazel_lib//tools/lint/py:black.bzl", "py_lint")
load("@svetoch_bazel_lib_py_deps//:requirements.bzl", "requirement")
load(":prepare.bzl", "prepare")

py_lint()

prepare()

py_binary(
    name = "tfvars",
    srcs = ["tfvars.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@svetoch_bazel_lib//libs/py/helpers",
        requirement("click"),
    ],
)
