ingresses:
  alertmanager-main:
    enabled: true
  prometheus-main:
    enabled: true
  prometheus-main-thanos:
    enabled: true

operator:
  enabled: true
  prometheusOperator:
    enabled: true

alertmanager-configs:
  enabled: true
  configs:
    main:
      enabled: true
      receivers: "{{ .Values.global.alerts.receivers | toYaml }}"

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true

kong-plugins:
  enabled: true

alertmanager-main:
  enabled: true

prometheus-main:
  enabled: true

prometheus-blackbox-exporter:
  enabled: true

prometheus-rules:
  enabled: true
  PrometheusAlerts:
    prometheus-main:
      AbsentMetricCritical:
        enabled: true
        rules:
          probe_success:
            enabled: true
          kong_http_requests_total:
            enabled: true
          pg_stat_database_xact_commit:
            enabled: true
          pg_up:
            enabled: true
          pg_stat_activity_count:
            enabled: true
      CriticalMetric:
        enabled: true
        interval: "31s"
        rules:
          #Kong (nginx)
          ErrorRateIncreasedFor_5XX:
            enabled: true
          # Blackbox
          api:
            enabled: true
          # Postgres
          Postgres_is_down:
            enabled: true
          Postgres_replica_is_down:
            enabled: true
          Available_postgresql_connections_are_running_out:
            enabled: true
          DB_transactions_per_seconds_below_norm:
            enabled: true
          # Resources
          OOM_killed_pods:
            enabled: true
          PVC_low_capacity:
            enabled: true
          # k8s
          Pods_waiting_state:
            enabled: true
          Pods_waiting_state_kube-system:
            enabled: true
          Pod_replicas_not_ready:
            enabled: true
          Daemonset_not_ready:
            enabled: true
          Statefulset_not_ready:
            enabled: true
          # rmq
          RabbitMQ_High_memory(watermark)_usage:
            enabled: true
          # redis
          Redis_missing_master:
            enabled: true
          Redis_too_many_masters:
            enabled: true
      WarningMetric:
        enabled: true
        rules:
          # redis
          Redis_disconnected_slaves:
            enabled: true
          # postgres
          Postgres_logical_backup_error:
            enabled: true
          # Resources
          PVC_low_capacity:
            enabled: true
          High_postgres_container_cpu_throttling:
            enabled: true
          High_cpu_throttling:
            enabled: true
          High_memory_usage:
            enabled: true
          OOM_killed_pods_(on_node):
            enabled: true
          # Deployment
          Container_too_many_restarts:
            enabled: true
