load(
    "@rules_tf//tf:defs.bzl",
    "tf_apply",
    "tf_binary",
    "tf_fmt_test",
    "tf_init",
    "tf_plan",
    "tf_fmt",
    "tf_validate_test",
)
load("@aspect_bazel_lib//lib:expand_template.bzl", "expand_template")
load("@aspect_bazel_lib//lib:copy_file.bzl", "copy_file")
load("@tfvars//:json.bzl", "tfvars")

ENV_NAME = package_name().split("/")[-2]

expand_template(
    name = "main_tf",
    substitutions = {
      "{COMPANY_NAME}": tfvars["company"]["name"],
      "{ENV_NAME}": tfvars["envs"][ENV_NAME]["name"],
    },
    template = ":main.tf",
)

expand_template(
    name = "tf_variables_tf",
    substitutions = {
      #We are not using {ENV_NAME} in order for
      #linter to work properly
      "ENV_NAME": tfvars["envs"][ENV_NAME]["name"],
    },
    template = ":tf_variables.tf",
)

filegroup(
    name = "srcs",
    srcs = glob(
        [
            "*.tf",
            "*.tfvars.json"
        ],
        exclude = [
          "main.tf",
          "tf_variables.tf"
        ],
    ) + [
        ":main_tf",
        ":tf_variables_tf",
    ],
    visibility = ["//visibility:__pkg__"],
)

filegroup(
    name = "srcs_lint",
    srcs = glob(
        [
            "*.tf",
            "*.tfvars.json"
        ],
    ),
)

tf_validate_test(
    name = "validate",
    srcs = [":srcs"],
    init = ":init_for_tests",
)

tf_fmt_test(
    name = "fmt",
    srcs = [":srcs_lint"],
)

tf_init(
    name = "init",
    srcs = [
        ":main_tf",
    ],
    tags = ["manual"],
)

tf_init(
    name = "init_for_tests",
    srcs = [
        ":main_tf",
    ],
    backend = False,
)

tf_plan(
    name = "plan",
    srcs = [":srcs"],
    init = ":init",
    parallelism = "100",
    tags = ["manual"],
)

tf_apply(
    name = "apply",
    srcs = [":srcs"],
    init = ":init",
    plan = ":plan",
    tags = ["manual"],
)

tf_binary(
    name = "tf",
    srcs = [":srcs"],
    init = ":init",
    tags = ["manual"],
)

tf_fmt(
    name = "fmt_fix",
    srcs = [
        ":srcs_lint",
    ],
    fix  = True,
    tags = ["manual"],
)
