ingresses:
  storegateway:
    enabled: true

kong-plugins:
  enabled: true

thanos:
  enabled: true
  compactor:
    enabled: true
    nodeSelector:
      apps-spot: "true"
    tolerations:
    - key: "apps-spot"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  storegateway:
    enabled: true
    nodeSelector:
      apps-spot: "true"
    tolerations:
    - key: "apps-spot"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
