cert-manager:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 200m
      memory: 100Mi
  nodeSelector:
    apps-spot: "true"
  tolerations:
  - key: "apps-spot"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 100Mi
    nodeSelector:
      apps-spot: "true"
    tolerations:
    - key: "apps-spot"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
      limits:
        cpu: 200m
        memory: 100Mi
    nodeSelector:
      apps-spot: "true"
    tolerations:
    - key: "apps-spot"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
