cert-manager:
  enabled: true
  nodeSelector:
    apps-spot: "true"
  tolerations:
  - key: "apps-spot"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  cainjector:
    nodeSelector:
      apps-spot: "true"
    tolerations:
    - key: "apps-spot"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  webhook:
    nodeSelector:
      apps-spot: "true"
    tolerations:
    - key: "apps-spot"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
