rabbitmq-cluster-operator:
  enabled: true

rabbitmq-main:
  enabled: true
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "example"
  replicas: 3
  resources:
    limits:
      cpu: 1500m
      memory: 6000Mi
    requests:
      cpu: 50m
      memory: 250Mi
  override:
    statefulSet:
      spec:
        template:
          metadata:
            labels:
              #proper labeling is needed for
              #observability
              app.kubernetes.io/instance: '{{ include "rabbitmq-cluster.fullname" . }}'
  persistence:
    storageClassName: premium-rwo
    storage: 10Gi
  vhosts:
    example:
      default_queue_type: quorum
  serviceMonitor:
    enabled: true
