name: master

env:
  BAZEL_RUN_TARGETS: "apply"
  CI_BUILDS_DIR: "/__w/${{ github.event.repository.name}}"
  CI_PROJECT_PATH: "${{ github.event.repository.name }}"
  GIT_HEAD_REF: ${{ github.head_ref }}

on:
  push:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    if: "github.event.head_commit.message != 'CI/CD: add new image tag'"
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: "${{ github.workspace }}/key.json"
    container:
      image: "gcr.io/bazel-public/bazel:7.4.0"
      #Needed because actions/checkout
      #needs the same user as it runs-on
      #or root
      options: --user 0
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "/home/ubuntu/.cache/bazel/"
        key: bazel
    # This is needed because
    # scripts/ci/{build,run}_targets.sh
    # need to get commit history
    - name: change folder permissions
      run: chown -R ubuntu .
    - name: export google creds
      run: |
        echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
    # Su is needed because py_* rules cant run
    # as root
    - name: prepare
      run: su ubuntu -c './scripts/ci/ci.sh prepare'
    - name: run
      run: su ubuntu -c './scripts/ci/ci.sh run'
