name: Pull requests

env:
  BAZEL_MANUAL_BUILD_TARGETS: "plan"
  CI_BUILDS_DIR: "/__w/${{ github.event.repository.name}}"
  CI_PROJECT_PATH: "${{ github.event.repository.name }}"
  BEFORE_COMMIT_SHA: ${{ github.event.pull_request.base.sha }}

on:
  pull_request:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "${{ vars.BAZELISK_IMAGE }}"
    steps:
    - name: Clone Git branch
      uses: actions/checkout@v7.0.1
    - name: test
      run: bazel test //...
